@startuml

'define icons
control Driver
participant "Job Committer"
control Executor
participant "Task Committer"
participant Operation
control "YARN NodeManager"
control "YARN ResourceManager"

' protocol
'== Initialization ==

Driver -> "Job Committer": setupJob()

== For Each Task Attempt ==
Driver -> Executor: execute work
Executor -> "Task Committer": setupTask()
Executor --> Operation: map/reduce
loop Until execution is complete...
  Executor -> Driver : ping?
  Driver -> Executor : task is known
  alt task is unknown/timeout/limits-exceeded
    Executor -> Executor: exit!
    Executor -> "YARN NodeManager": (exited)
    "YARN NodeManager" -> "YARN ResourceManager": process exited
  end
    Driver -> "YARN ResourceManager": heartbeat request
    Driver <-- "YARN ResourceManager": heartbeat response [exited tasks]*
end
Executor <-- Operation: map/reduce finished

'TODO: MR failure

Executor -> Driver: can commit?
Executor <-- Driver:  <commit | abort>

alt commit
  Executor -> "Task Committer": needsTaskCommit()?
  Executor <-- "Task Committer": <true | false>
    alt needs task commit
    Executor -> Driver: commitPending
    Executor -> "Task Committer": commitTask()
    Executor <-- "Task Committer": committed task
    end

else abort
  Executor -> "Task Committer": abortTask()
  Executor <-- "Task Committer": aborted task
end
Executor -> Driver : task commit/abort completed
Executor -> Executor: exit!
Executor -> "YARN NodeManager": (exited)
"YARN NodeManager" -> "YARN ResourceManager": process exited

alt done-not-received-in time interval
  Driver -> "Job Committer": cleanupTask()
  Driver -> Driver: reschedule task
end


== Job Commit==

Driver -> "YARN ResourceManager": heartbeat request
Driver <-- "YARN ResourceManager": heartbeat response [exited tasks]*

Driver -> "Job Committer": commitJob()
Driver <-- "Job Committer": committed job
Driver -> "Job Committer": cleanupJob()
Driver -> "YARN ResourceManager": finished
Driver -> Driver: exit!
Driver -> "YARN NodeManager": (exited)
"YARN NodeManager" -> "YARN ResourceManager": process exited


@enduml
